services:
  - type: web
    name: flappybird-game
    env: python
    plan: free
    buildCommand: |
      pip install -r requirements.txt
      python manage.py migrate
      python manage.py collectstatic --noinput
    startCommand: gunicorn flappybird_project.wsgi:application --bind 0.0.0.0:$PORT
    autoDeploy: true
    envVars:
      - key: SECRET_KEY
        value: your-very-secret-key-here
      - key: DEBUG
        value: 'False'
